name: workflow

on:
    push:
        branches:
            - main
        paths-ignore:
            - 'README.md'

jobs:
    integration:
        name: Continuous integration
        runs-on: ubuntu_latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Lint code
              run: echo "Linting Repository"

            - name: Run unit tests
              run: echo "Running unit tests"